"""empty message

Revision ID: 011af0bff029
Revises: e013cbd3b695
Create Date: 2023-11-06 13:25:12.800231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011af0bff029'
down_revision = 'e013cbd3b695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_memory_gb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limit_cpu_cores', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limit_disk_size_gb', sa.Integer(), nullable=True))

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('desktop_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('icon_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('apptainer_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('apptainer_file',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('icon_file',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('desktop_file',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('machine_provider', schema=None) as batch_op:
        batch_op.drop_column('limit_disk_size_gb')
        batch_op.drop_column('limit_cpu_cores')
        batch_op.drop_column('limit_memory_gb')

    # ### end Alembic commands ###
