"""empty message

Revision ID: 0d7ec3ca65d0
Revises: 78876c0b56fe
Create Date: 2023-09-08 10:00:38.696712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7ec3ca65d0'
down_revision = '78876c0b56fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_last_time_confirmed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_last_time_confirmed')

    # ### end Alembic commands ###
