"""empty message

Revision ID: 1a5680f9b4cb
Revises: e0c5b647dae3
Create Date: 2023-06-15 20:59:33.473412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a5680f9b4cb"
down_revision = "e0c5b647dae3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "software",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image_provider",
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("machine_provider_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name="fk_image_provider_image_id"
        ),
        sa.ForeignKeyConstraint(
            ["machine_provider_id"],
            ["machine_provider.id"],
            name="fk_image_provider_machine_provider_id",
        ),
        sa.PrimaryKeyConstraint(
            "image_id", "machine_provider_id", name="pk_image_provider"
        ),
    )
    op.create_table(
        "software_image",
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name="fk_software_image_image_id"
        ),
        sa.ForeignKeyConstraint(
            ["software_id"], ["software.id"], name="fk_software_image_software_id"
        ),
        sa.PrimaryKeyConstraint("software_id", "image_id", name="pk_software_image"),
    )
    with op.batch_alter_table("machine_template", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_machine_template_image_id", "image", ["image_id"], ["id"]
        )
        batch_op.drop_column("image")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("machine_template", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image", sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint("fk_machine_template_image_id", type_="foreignkey")
        batch_op.drop_column("image_id")

    op.drop_table("software_image")
    op.drop_table("image_provider")
    op.drop_table("software")
    op.drop_table("image")
    # ### end Alembic commands ###
