"""empty message

Revision ID: 2b65e962a2f4
Revises: 0d7ec3ca65d0
Create Date: 2023-09-08 10:53:01.933144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b65e962a2f4'
down_revision = '0d7ec3ca65d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), nullable=False))
        batch_op.drop_column('otp_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_confirmed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('otp_enabled')

    # ### end Alembic commands ###
