"""empty message

Revision ID: 350e7dedb23c
Revises: 1a5680f9b4cb
Create Date: 2023-07-02 07:11:14.248114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "350e7dedb23c"
down_revision = "1a5680f9b4cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "import_name", sa.String(length=256), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.drop_column("is_enabled")
        batch_op.drop_column("import_name")

    # ### end Alembic commands ###
