"""empty message

Revision ID: 3c737933e1bf
Revises: f8f34ceb764c
Create Date: 2023-09-05 10:50:58.142944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c737933e1bf'
down_revision = 'f8f34ceb764c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_machine_machine_rovider', 'machine_provider', ['machine_provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machine_machineprovider', type_='foreignkey')
        batch_op.drop_column('machine_provider_id')

    # ### end Alembic commands ###
