"""empty message

Revision ID: 4dbf01966a38
Revises: 350e7dedb23c
Create Date: 2023-07-24 11:03:09.950929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbf01966a38'
down_revision = '350e7dedb23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_machine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('machine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_data_source_machine_id', 'machine', ['machine_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_source_machine_id', type_='foreignkey')
        batch_op.drop_column('machine_id')
        batch_op.drop_column('is_machine')

    # ### end Alembic commands ###
