"""empty message

Revision ID: 4dbf01966a38
Revises: 350e7dedb23c
Create Date: 2023-07-24 11:03:09.950929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbf01966a38'
down_revision = '350e7dedb23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_data_source')
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_machine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('machine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_data_source_machine_id', 'machine', ['machine_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_source_machine_id', type_='foreignkey')
        batch_op.drop_column('machine_id')
        batch_op.drop_column('is_machine')

    op.create_table('_alembic_tmp_data_source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('source_username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source_host', sa.VARCHAR(length=256), nullable=False),
    sa.Column('source_port', sa.INTEGER(), nullable=False),
    sa.Column('source_dir', sa.VARCHAR(length=256), nullable=False),
    sa.Column('data_size', sa.INTEGER(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.Column('import_name', sa.VARCHAR(length=256), server_default=sa.text("('')"), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_machine', sa.BOOLEAN(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name='fk_data_source_machine_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_source_name')
    )
    # ### end Alembic commands ###
