"""empty message

Revision ID: 52f7c6958c4e
Revises: d43197ad6595
Create Date: 2023-09-07 13:03:47.887108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f7c6958c4e'
down_revision = 'd43197ad6595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_enabled', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
