"""empty message

Revision ID: 6a5a26cb3124
Revises: 350e7dedb23c
Create Date: 2023-07-25 15:21:40.014839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5a26cb3124'
down_revision = '350e7dedb23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_data_transfer_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('RUNNING', 'DONE', 'FAILED', 'HIDDEN', name='datatransferjobstate'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], "fk_machine_data_transfer_job_machine_id"),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], "fk_machine_data_transfer_job_user_id"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_data_transfer_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_data_transfer_job_state'), ['state'], unique=False)

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_data_transfer_job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_audit_machine_data_transfer_job_id", 'machine_data_transfer_job', ['machine_data_transfer_job_id'], ['id'])

    with op.batch_alter_table('problem_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_data_transfer_job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_problem_report_machine_data_transfer_job_id", 'machine_data_transfer_job', ['machine_data_transfer_job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_report', schema=None) as batch_op:
        batch_op.drop_constraint("fk_problem_report_machine_data_transfer_job_id", type_='foreignkey')
        batch_op.drop_column('machine_data_transfer_job_id')

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_constraint("fk_audit_machine_data_transfer_job_id", type_='foreignkey')
        batch_op.drop_column('machine_data_transfer_job_id')

    with op.batch_alter_table('machine_data_transfer_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_data_transfer_job_state'))

    op.drop_table('machine_data_transfer_job')
    # ### end Alembic commands ###
