"""empty message

Revision ID: 78876c0b56fe
Revises: 52f7c6958c4e
Create Date: 2023-09-08 09:52:48.415910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78876c0b56fe'
down_revision = '52f7c6958c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_secret',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_secret',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
