"""empty message

Revision ID: 831383c40702
Revises: bb697275472b
Create Date: 2023-08-08 12:48:18.826746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "831383c40702"
down_revision = "bb697275472b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_email_confirmed",
                sa.Boolean(),
                nullable=False,
                server_default="False",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_email_confirmed")

    # ### end Alembic commands ###
