"""empty message

Revision ID: 8e73e5f1123e
Revises: 350e7dedb23c
Create Date: 2023-07-26 11:13:37.228467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e73e5f1123e"
down_revision = "350e7dedb23c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_transfer_job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("machine2_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_datatransferjob_machine2", "machine", ["machine2_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_transfer_job", schema=None) as batch_op:
        batch_op.drop_constraint("fk_datatransferjob_machine2", type_="foreignkey")
        batch_op.drop_column("machine2_id")

    # ### end Alembic commands ###
