"""empty message

Revision ID: 9ff163200b72
Revises: 8e186b4a4a0c
Create Date: 2023-08-23 10:25:51.064403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff163200b72'
down_revision = '8e186b4a4a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_approved_users', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('pre_approved_users')

    # ### end Alembic commands ###
