"""empty message

Revision ID: a77601577b0e
Revises: f8f34ceb764c
Create Date: 2023-09-08 11:04:59.067825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77601577b0e'
down_revision = 'f8f34ceb764c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('otp_last_time_confirmed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_last_time_confirmed')
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
