"""empty message

Revision ID: bb697275472b
Revises: 7b4637498891
Create Date: 2023-08-06 09:06:26.233659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb697275472b"
down_revision = "7b4637498891"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_build_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("template_name", sa.String(length=100), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "STARTING",
                "MAKING_VM",
                "COPYING_BUILD",
                "WAITING_FOR_VM",
                "RUNNING_SCRIPT",
                "SAVING_IMAGE",
                "DONE",
                "FAILED",
                name="imagebuildjobstate",
            ),
            nullable=False,
        ),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("finished_date", sa.DateTime(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("machine_provider_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], name="fk_image_id_image"),
        sa.ForeignKeyConstraint(
            ["machine_provider_id"],
            ["machine_provider.id"],
            name="fk_machine_provider_id_machine_provider",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image_build_job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_build_job_state"), ["state"], unique=False
        )

    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    with op.batch_alter_table("image_build_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_build_job_state"))

    op.drop_table("image_build_job")
    # ### end Alembic commands ###
