"""empty message

Revision ID: bf201fcd5449
Revises: 3c737933e1bf
Create Date: 2023-09-18 09:05:48.273971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf201fcd5449"
down_revision = "3c737933e1bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("otp_secret", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "otp_enabled",
                sa.Boolean(),
                server_default=sa.sql.expression.false(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("otp_last_time_confirmed", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("otp_last_time_confirmed")
        batch_op.drop_column("otp_enabled")
        batch_op.drop_column("otp_secret")

    # ### end Alembic commands ###
