"""empty message

Revision ID: d2f886d1e39d
Revises: 7b4637498891
Create Date: 2023-08-04 14:36:49.221216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f886d1e39d'
down_revision = '7b4637498891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_confirmed', sa.Boolean(), nullable=False, server_default='False'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_email_confirmed')

    # ### end Alembic commands ###
