"""software table update

Revision ID: e013cbd3b695
Revises: bf201fcd5449
Create Date: 2023-11-02 15:47:22.792085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e013cbd3b695'
down_revision = 'bf201fcd5449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('desktop_file', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('icon_file', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('apptainer_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_column('apptainer_file')
        batch_op.drop_column('icon_file')
        batch_op.drop_column('desktop_file')
        batch_op.drop_column('version')
        batch_op.drop_column('description')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
