"""empty message

Revision ID: e0c5b647dae3
Revises: a9178fb76032
Create Date: 2023-05-30 17:23:36.923502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0c5b647dae3"
down_revision = "a9178fb76032"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_welcome_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["group.id"], name="fk_group_welcome_page_group_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_data_source_name", ["name"])

    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_public",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )

    with op.batch_alter_table("machine_provider", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_machine_provider_name", ["name"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_banned",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_group_admin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(sa.Column("extra_data", sa.JSON(), nullable=True))
        batch_op.create_unique_constraint("uq_user_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("extra_data")
        batch_op.drop_column("is_group_admin")
        batch_op.drop_column("is_banned")

    with op.batch_alter_table("machine_provider", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.drop_column("is_public")

    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.drop_table("group_welcome_page")
    # ### end Alembic commands ###
