"""empty message

Revision ID: e876d7136068
Revises: 9415d7f6adfb
Create Date: 2023-09-07 10:11:57.978589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e876d7136068'
down_revision = '9415d7f6adfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
