"""empty message

Revision ID: f4e42d191f8b
Revises: 4dbf01966a38
Create Date: 2023-07-24 11:30:25.522171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e42d191f8b'
down_revision = '4dbf01966a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.alter_column('is_machine',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.alter_column('is_machine',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
