"""empty message

Revision ID: f8f34ceb764c
Revises: 0612d1022af0
Create Date: 2023-08-24 10:53:44.650029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f34ceb764c'
down_revision = '0612d1022af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_machine_image', 'image', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machine_image', type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
